name: Release to production

on:
  push:
    branches: [ "main" ]

jobs:

  # First ensure that the contents are valid by running the linter.
  lint-and-release:

    runs-on: ubuntu-latest
    steps:
      # Checkout local patterns markdown
      - uses: actions/checkout@v3

      # Install Node and NPM dependencies
      - name: Use Node.js v18.x
        uses: actions/setup-node@v3
        with:
          node-version: v18.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present

      # Run the linter to validate pattern markdown content
      - run: npm run-script lint

      # Use a Github PAT to dispatch a release request to the private infrastructure repo
      - name: Dispatch release request
        # The release request will fail anyway if a fork tries to run it
        # because they won't have the right PAT
        if: github.repository_owner == 'aws-samples'
        run: |
          curl -v -X POST https://api.github.com/repos/Project-Gretchen/infrastructure/dispatches \
          -H "Authorization: token ${GITHUB_TOKEN}" \
          -H "Content-Type: application/json" \
          --data-binary @- << EOF
            {
              "event_type": "pattern_release",
              "client_payload": {
                 "patterns_repo": "${GITHUB_REPOSITORY}",
                 "message": "Release to production by merge to main"
              }
            }
          EOF
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
