name: Validate PR

on:
  pull_request:
    branches: [ "main" ]

jobs:

  # First ensure that the contents are valid by running the linter
  lint-data:

    runs-on: ubuntu-latest
    steps:
      # Checkout local patterns markdown
      - uses: actions/checkout@v3

      # Install Node and NPM dependencies
      - name: Use Node.js v18.x
        uses: actions/setup-node@v3
        with:
          node-version: v18.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present

      # Run the linter to validate pattern markdown content
      - run: npm run-script lint

  # Dispatch a preview request to the infrastructure repo
  request-preview:
    needs:
      - lint-data
    runs-on: ubuntu-latest
    steps:

      # Use a Github PAT to dispatch a release request to the private infrastructure repo
      - name: Dispatch preview request
        run: |
          curl -X POST https://api.github.com/repos/Project-Gretchen/infrastructure/dispatches \
          -H "Authorization: token ${GITHUB_TOKEN}" \
          -H "Content-Type: application/json" \
          --data '{"event_type": "Pattern PR preview: ${{ github.event.pull_request.title }}", "client_payload": { "patterns_ref": "'"$GITHUB_SHA"'", "pr_id": "${{ github.event.pull_request.id }}" }}'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
